const express = require("express");
const router = express.Router();
const musics = require("./musics");
const artists = require("./artists");
const genres = require("./genres");
const users = require("./users");
const roles = require("./roles");
router.use("/musics", musics);
router.use("/artists", artists);
router.use("/genres", genres);
router.use("/users", users);
router.use("/roles", roles);
module.exports = router;
