const express = require("express");
const { validation, loginSchema } = require("../middlewares/joiValidation");
const { joiSchema } = require("../models/user");
const paginate = require("../middlewares/paginate");
const { protect, authorize } = require("../middlewares/auth");
const { register, login, index } = require("../controllers/authController");
const router = express.Router();
router.post("/register", validation(joiSchema), register);
router.post("/login", validation(loginSchema), login);
router.route("/").get(protect, authorize(10), paginate, index);
module.exports = router;
